# Jobs run on pull request in js folders
name: Pull request JS
on:
  pull_request:
    branches:
      - main
    paths: # Only run when changes are made to js code
      - "packages/@naql/**"
      - "packages/runtime/**"
      - "package.json"
      - "yarn.lock"

# Cancel jobs when the PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format-js:
    name: Check JS Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Run Biome CI check
        run: |
          yarn install --immutable
          yarn biome ci
